version: 0.0
os : linux
files :
 - source : /
   destination: /home/ubuntu/app/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: beforeinstall.sh
  AfterInstall:
    - location: afterinstall.sh
  ApplicationStart:
    - location : deploy.sh
      timeout: 60
      runas: ubuntu

# This section controls the action:
branch_config:
    wip\/.*: ~
    master:
        deploymentGroupName: djangocrudboard-group
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::058718939924:role/codedeploy-role
        deploymentConfig:
            autoRollbackConfiguration:
                enabled: false
