version: '3'

networks:
  app-tier:
    driver: bridge

services:
  gunicorn-backend:
    container_name: gunicorn-backend
    build: .
    volumes:
      - .:/code
    networks:
      - app-tier
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    # depends_on:
    #   - migration

  # migration:
  #     image: app
  #     command: sh -c "pipenv run python manage.py migrate"
  #     volumes:
  #         - .:/code
  #     # links:
  #     #     - mysql_db
  #     depends_on:
  #         - make_migrations
  
  # make_migrations:
  #     image: app
  #     command: sh -c "pipenv run python manage.py makemigrations"
  #     volumes:
  #         - .:/code
  #     # links:
  #     #     - mysql_db
  #     # depends_on:
  #     #     - mysql_db
      
  nginx-backend:
    container_name: nginx-backend
    image: nginx:latest
    volumes:
    - ./nginx/nginx-app.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/logs:/var/DjangoCRUDBoard-logs
    expose:
    - "80"
    ports:
    - "80:80"
    networks:
    - app-tier
    depends_on:
    - gunicorn-backend
    environment:
    - NGINX_HOST=0.0.0.0
    - NGINX_PORT=80