name: CI
on:
  push:
    branches:
    - feature-dockerize
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0

