name: CI
on:
  push:
    branches:
    - master
    - feature-dockerize
    
jobs:
  docker-build:
      runs-on: ubuntu-latest
      steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: a891/djangocrudboard:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  upload:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload S3 for Codedeploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'   # optional: defaults to us-east-1
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: Configuring aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Triggering AWS codedeploy
      uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
