name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Pyenv install
      run: curl https://pyenv.run | bash
      
    - name: install Pipenv - 1
      run: sudo pip install pipenv
      
    - name: install Pipenv - 2
      run: pipenv install 
    
    - name: Fetch requirements.txt
      run: pipenv lock -r > requirements.txt

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: DjangoCRUDBoard
        environment_name: Djangocrudboard-env-2
        version_label: ${{ github.sha }}
        region: ap-northeast-2
        deployment_package: deploy.zip
